#!/bin/sh

case "${1}" in
	hibernate|suspend)
		# Pause sound system
		alsa suspend all

		# Unbind ehci for preventing error
		echo -n "0000:00:1d.0" | tee /sys/bus/pci/drivers/ehci-pci/unbind
		# Unbind snd_hda_intel for sound
		echo -n "0000:00:1b.0" | tee /sys/bus/pci/drivers/snd_hda_intel/unbind
		echo -n "0000:00:03.0" | tee /sys/bus/pci/drivers/snd_hda_intel/unbind

		# Do not inhibit sleep if the above commands return non-zero exit codes.
		exit 0
	;;
	resume|thaw)
		# Unbind ehci for preventing error
		echo -n "0000:00:1d.0" | tee /sys/bus/pci/drivers/ehci-pci/unbind
		# Bind snd_hda_intel for sound
		echo -n "0000:00:1b.0" | tee /sys/bus/pci/drivers/snd_hda_intel/bind
		echo -n "0000:00:03.0" | tee /sys/bus/pci/drivers/snd_hda_intel/bind

		# Resume sound system
		alsa resume
		# Restart pulseaudio
		killall pulseaudio
	;;

esac
